### ISSUE TITLE
Consider using TOML instead of INI

### ISSUE THREAD

**Issue by CodingVoid** [hughsie/python-uswid#27]
TOML is a simple file format and very similiar to INI. But in contrast to INI, TOML has an actual specification and supports array types, which could be usefull for the entity roles and other array types of CoSWID. This is merely a suggestion and probably something for later, but I didn't want to forget it, so I am writing it down now. Just to clarify: I suggest replacing INI instead of adding TOML as just another file format of which we support quite enough already.

**Comment by hughsie** [comment]
I think stick to ini as it's something people are familiar with in the Windows world. Sorry!
